export default {
  activities: {
    angry: ['draw', 'bubblepop', 'music', 'breathing' ],
    annoyed:  ['draw', 'bubblepop', 'music', 'breathing' ],
    frustrated: ['draw', 'breathing' ],
    exasperated: ['breathing', 'bubblepop'],
    argumentative: ['draw', 'music'],
    vengeful: ['draw', 'breathing'],
    furious: ['draw', 'breathing'],
    afraid: ['bubblepop', 'breathing'],
    nervous: ['draw', 'breathing'],
    anxious: ['draw', 'breathing'],
    dread: ['bubblepop', 'breathing'],
    desperate: ['bubblepop', 'breathing'],
    panicked: ['bubblepop', 'draw'],
    terrified: ['bubblepop', 'draw', 'breathing'],
    disgusted: ['music', 'draw', 'breathing'],
    dislike: ['music', 'draw', 'bubblepop'],
    repulsed: ['music', 'draw', 'breathing'],
    aversion: ['music', 'draw', 'breathing'],
    distaste: ['music', 'draw', 'bubblepop'],
    revulsed: ['music', 'draw', 'bubblepop'],
    loathing: ['music', 'draw', 'breathing'],
    sad: ['music', 'draw', 'breathing'],
    disappointed: ['music', 'draw', 'bubblepop'],
    discouraged: ['music', 'draw', 'bubblepop'],
    hopeless: ['music', 'draw'],
    miserable: ['breathing', 'draw'],
    sorrowful: ['music', 'draw'],
    melancholy: ['music', 'draw'],
    joyful: ['music', 'draw'],
    compassionate: ['music', 'draw'],
    amused: ['breathing', 'draw'],
    relieved: ['breathing', 'draw', 'bubblepop'],
    peaceful: ['breathing', 'draw', 'bubblepop', 'music'],
    proud: ['breathing', 'draw', 'music'],
    wonder: ['bubblepop', 'draw', 'music'],
    excited: ['breathing', 'bubblepop', 'music'],
    ecstatic: ['breathing', 'draw', 'music'],
  }
}
